name: Build Debian Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Package version (e.g. 1.0.0)"
        required: true
        default: "1.0.0"

permissions:
  contents: write

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show directory structure
        run: |
          pwd
          ls -la
          tree -L 2
          
